name: Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Set up Azure
#     uses: azure/CLI@v1
#      with:
#       azure-cli-version: latest

    - name: Login to Azure
      run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    
    - name: Install Bicep
      run: |
        npm install -g @bicep/cli
    
    - name: Build and Deploy
      run: bicep build main.bicep && az deployment group create --resource-group myResourceGroup --template-file main.json
