name: Deploy to Azure
env:
  ACTIONS_RUNNER_DEBUG: true
on:
  push:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./acr.bicep
        parameters: SPapplicationId=${{ secrets.AZURE_SP_APP_ID }} SPobjectId=${{ secrets.AZURE_SP_APP_ID }}
        
        failOnStdErr: false
